### PR TITLE
Added async calls to the server

### LINKED ISSUE #464: Server not always loading up instantly after the systemd service is executed
#### Describe the bug
Server not always loading up instantly after the systemd service is executed and the pi changes to the online server instead.

#### To Reproduce
1. Try restarting the speaker again and again.
2. it will show a line saying server is down

#### Expected behavior
To connect to the local server as soon as available.

#### Additional context
I'll be writing an async method that switches to local server as soon as available.

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #464 

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [x] The unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [x] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

### CODE REVIEW

**Comment by stealthanthrax** [comment]
Dependant on PR(https://github.com/fossasia/susi_api_wrapper/pull/75)

**Comment by hongquan** [comment]
Only today I look into susi_api_wrapper code and found that it is using `global` variable. This practice is discouraged in Python, especially dangerous when it is used in multi-threaded app. Modifying shared state is the source of crash.

So, I don't want to merge this PR. I leave it for other reviewers.

**Comment by stealthanthrax** [comment]
So, there are two possible solutions that I have in my mind.
1. One is that I use an already existing function in the App but it'll still use global variables. But since the multithreading is being done in the client side and the global variables are being used in the API wrapper , so I believe it should not be a problem.

2. Convert the complete wrapper into an OOP model and remove the FP part. (Better Practice) . However, it can maybe lead to some bugs and I don't want that to happen it before the FOSSASIA Summit.(But we can convert it after the Summit)

@hongquan , what do you suggest?

**Comment by hongquan** [comment]
The option 1 sounds more reasonable, because it moved "multi-threading" to app, not the lib (API wrapper). "global" variables still exists, but need to be removed some day.

The option 2 sounds weird when you think that FP is worse than OOP, especially in the case of multi-threading. FP is better than OOP in multi-threading programming. Maybe just your typo mistake?

**Comment by Orbiter** [comment]
I am unsure what to do here. One point is that it is good to discuss a good coding style, another is to get things running in any way to make FOSSASIA next week a success. I am bringing 14 devices to sell there, so everything should work!
As Argument 1 is absolutely valid we should not stop here because of technical debts.

**Comment by Orbiter** [comment]
This created a crash and had to be reverted:
https://github.com/fossasia/susi_linux/commit/ac22e79e85a52a6be8ac862e1794254552fef3a6

**Comment by stealthanthrax** [comment]
Sorry for that 😓 . Log shows that it crashed because of the dependent PR not being merged. I'll make the fix in a single PR without altering the lib after the summit
> This created a crash and had to be reverted:

**Pull request merged**
