### PR TITLE
Added steps to use piHat as default sound card

### LINKED ISSUE #216: To Add documentation and installation regarding the ReSpeaker
Current Behavior
No documentation regarding the ReSpeaker present

Expected Behaviour
To add the respected documentation

Would you like to work on this issue?
Yes

### LINKED ISSUE #282: To Configure PiHat's Microphone to work as a default
**Describe the bug**
Right now, the pi Hat's led works with SUSI Smart Speaker, but the mic doesn't with it.

**To Reproduce**
To use to mic , we have to use the command `arecord` , but the stt services use the `rec` command.

**Expected behavior**
To find a configuration, that will configure the piHat as the default sound card for the `sox` libraries.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #282 
Fixes #216 

This PR adds instructions on how to configure piHat as the default audio device for SUSI Linux

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@mariobehling @Orbiter @woshikie @hongquan @cweitat , these are just the instructions that I have added in the PR , should we also implement this feature automatically too??
Asking this query , as implementing the feature automatically will disable the default audio cards and will cause issues for the people without the piHat.

**Comment by cweitat** [comment]
@stealthanthrax you have already mentioned that by disabling the default audio cards will cause issues for those without piHat. So we leave it installing piHat as a default optional. Anyway the ultimate goal is also to breakaway from using only RPi and not supporting only one variant of sound card.

Wait for others' views.

**Comment by stealthanthrax** [comment]
Actually, @cweitat , using this method will support any piHat. But I also think that we should not disable the default audio drivers by default.

**Comment by cweitat** [comment]
@stealthanthrax what I meant was that we can use other boards for SUSI other than RPi. I assume when you say piHat, it means HAT that is only for RPi.

**Comment by stealthanthrax** [comment]
@woshikie , i have suggested an approach using `pacmd` . But this sometimes doesn't work , so I have also kept the current approach like that

**Comment by stealthanthrax** [comment]
@cweitat , if we use the command `pacmd set-default-sink 1`, the sound stops coming out of the default ports and mic is change to the one on piHat. But still there is no sound from the 3.5 mm jack present on piHat

**Comment by woshikie** [comment]
@stealthanthrax 
im not sure what you did, but `pacmd set-default-sink 1` is setting the audio output(speakers/headphones), not the input(microphone)

From what i see, the default port for after doing `pacmd set-default-sink 1` is the speaker port, but you are using the 3.5mm audio jack, which is the headphones port. So you will need to do `pacmd set-sink-port alsa_output.platform-soc_sound.analog-stereo analog-output-speaker` to change the audio output to the headphone jack.

**Comment by woshikie** [comment]
@stealthanthrax 
more into my previous reply,

you can find more details about your current available sinks by doing
`pactl list sinks`

<details><summary>Here's my output for an exmaple</summary>

```
pi@raspberrypi:~ $ pactl list sinks
Sink #0
        State: SUSPENDED
        Name: alsa_output.platform-soc_audio.analog-stereo
        Description: bcm2835 ALSA Analog Stereo
        Driver: module-alsa-card.c
        Sample Specification: s16le 2ch 48000Hz
        Channel Map: front-left,front-right
        Owner Module: 6
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Base Volume: 56210 /  86% / -4.00 dB
        Monitor Source: alsa_output.platform-soc_audio.analog-stereo.monitor
        Latency: 0 usec, configured 0 usec
        Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY
        Properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "bcm2835 ALSA"
                alsa.id = "bcm2835 ALSA"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "0"
                alsa.card_name = "bcm2835 ALSA"
                alsa.long_card_name = "bcm2835 ALSA"
                device.bus_path = "platform-soc:audio"
                sysfs.path = "/devices/platform/soc/soc:audio/bcm2835_alsa/sound/card0"
                device.string = "hw:0"
                device.buffering.buffer_size = "131072"
                device.buffering.fragment_size = "131072"
                device.access_mode = "mmap+timer"
                device.profile.name = "analog-stereo"
                device.profile.description = "Analog Stereo"
                device.description = "bcm2835 ALSA Analog Stereo"
                alsa.mixer_name = "Broadcom Mixer"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card"
        Ports:
                analog-output: Analog Output (priority: 9900)
        Active Port: analog-output
        Formats:
                pcm

Sink #1
        State: SUSPENDED
        Name: alsa_output.platform-soc_sound.analog-stereo
        Description: seeed-2mic-voicecard Analog Stereo
        Driver: module-alsa-card.c
        Sample Specification: s16le 2ch 48000Hz
        Channel Map: front-left,front-right
        Owner Module: 7
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Base Volume: 52057 /  79% / -6.00 dB
        Monitor Source: alsa_output.platform-soc_sound.analog-stereo.monitor
        Latency: 0 usec, configured 0 usec
        Flags: HARDWARE HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY
        Properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = ""
                alsa.id = "bcm2835-i2s-wm8960-hifi wm8960-hifi-0"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "1"
                alsa.card_name = "seeed-2mic-voicecard"
                alsa.long_card_name = "seeed-2mic-voicecard"
                alsa.driver_name = "snd_soc_simple_card"
                device.bus_path = "platform-soc:sound"
                sysfs.path = "/devices/platform/soc/soc:sound/sound/card1"
                device.string = "hw:1"
                device.buffering.buffer_size = "352800"
                device.buffering.fragment_size = "176400"
                device.access_mode = "mmap+timer"
                device.profile.name = "analog-stereo"
                device.profile.description = "Analog Stereo"
                device.description = "seeed-2mic-voicecard Analog Stereo"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card"
        Ports:
                analog-output-speaker: Speakers (priority: 10000)
                analog-output-headphones: Headphones (priority: 9000)
        Active Port: analog-output-headphones
        Formats:
                pcm
```
</details>

as you can see, the seeed voice card has 2 ports
```
        Ports:
                analog-output-speaker: Speakers (priority: 10000)
                analog-output-headphones: Headphones (priority: 9000)
        Active Port: analog-output-headphones
```
my current Active Port is 
`analog-output-headphones`

When I first did `pactl list sinks`, my Active port was
`analog-output-speaker`
and i couldn't hear anything from the 3.5mm audio jack either.

So i did 
`pacmd set-sink-port alsa_output.platform-soc_sound.analog-stereo analog-output-speaker`
to change it to headphones port, and now I can listen from the 3.5mm audio jack.

as you can see from the command, it is as follows
`pacmd set-sink-port <sink name> <port name>`

**Comment by stealthanthrax** [comment]
Okay @woshikie . I'll update it accordingly

**Comment by stealthanthrax** [comment]
@woshikie , I have updated the README accordingly

**Comment by stealthanthrax** [comment]
@woshikie , the approach suggested by you still didn't work for me and might work for the others. So, I have added both approaches

**Comment by stealthanthrax** [comment]
@woshikie , how can a person use the 3.5 mm jack headphone present on the piHat??

**Comment by woshikie** [comment]
@stealthanthrax 
https://github.com/fossasia/susi_linux/pull/289#issuecomment-406792112

**Comment by stealthanthrax** [comment]
Yes @woshikie , updated

**Comment by hongquan** [comment]
Because Pi HAT is just a general name of add-on boards for Raspberry Pi (I mentioned this before), this sentence is ambiguous:

> To Use PiHat as a default sound card

Can it be more specific? Which board, which device?

**Comment by stealthanthrax** [comment]
@hongquan , updated

**Pull request merged**
