### PR TITLE
Added first step to the Server

### PR DESCRIPTION
**Pull request by stealthanthrax**
First step to #170 

Changes
I have created a basic python server that will start on the first bootup and will be removed when the wifi credentials are input

### CODE REVIEW

**Comment by mariobehling** [comment]
@stealthanthrax What is your plan for the following cases:
The Wifi password has changed and the user cannot access the device through the network anymore. How can the reset the device and get the access point open again to reconfigure the device with a new Wifi/password config?

**Comment by stealthanthrax** [comment]
@mariobehling , the user can use the factory reset option to reset his device.

**Comment by stealthanthrax** [comment]
@mariobehling , I was thinking of adding a compressed version of susi_linux repo inside the susi_linux  repo which we can extract and replace with the original repo

**Comment by mariobehling** [comment]
> I was thinking of adding a compressed version of susi_linux repo inside the susi_linux repo which we can extract and replace with the original repo

Ok, sounds like a good approach. Please open an issue about this.

We should also store as much as possible of the config of the device on the server. Think of the data that Google saves of your phone. When you change a phone you can have a lot of your data work on the new device as well.

**Pull request merged**
