### PR TITLE
Updated the installation docs

### LINKED ISSUE #234: Update the installation docs regarding configuring and running SUSI on the Raspberry Pi
I've been trying to setup Raspberry Pi 3 for several days now, and finally managed to configure and run SUSI on it yesterday. I think the installation docs are missing a few important steps. 
Hence, the installation docs should be updated with the proper procedure for configuring and running SUSI on the Raspberry Pi.

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #234 
Added a few steps in the installation docs, based on the issues I faced while configuring and running SUSI on Raspberry Pi 3.

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
@stealthanthrax Please review. Thanks :-)

**Comment by woshikie** [comment]
I do not think that `susi_linux` repository should be sitting in a predefined folder `SUSI.AI`. The install.sh script should be able to run as long as it is in the `susi_linux` folder, which is created when the user do `git clone https://github.com/fossasia/susi_linux` , or a folder of any other name as long as the folder structure and files stay the same inside.

**Comment by Akshat-Jain** [comment]
@woshikie I'm not sure exactly how the scripts work, but it didn't work for me when I was doing the steps in the root directory. @stealthanthrax told me to do the steps inside `SUSI.AI` folder and then it worked. Most scripts that I saw also had the path to the `susi_linux` folder like `pi/SUSI.AI/susi_linux`.

@stealthanthrax Your opinions on this please? Thanks :-)

**Comment by stealthanthrax** [comment]
@woshikie , we require the repo to be cloned inside the folder `SUSI.AI` for scripts like media_daemon and the scripts in the python server.

**Comment by woshikie** [comment]
@stealthanthrax I'll take a look and try to make that requirement optional

**Comment by Akshat-Jain** [comment]
@stealthanthrax @woshikie Made the required changes. Please review. Thanks :-)

**Comment by woshikie** [comment]
@hongquan have a look at this request too. Is it possible to run without creating the folder `SUSI.AI`

**Comment by woshikie** [comment]
This PR creates path issues
reference: #237

**Comment by hongquan** [comment]
> Is it possible to run without creating the folder SUSI.AI

@woshikie Currently, the code (Bash & Python) in this project still assumes that _susi_linux_ stays in _/home/pi/SUSI.AI_, and the hard-code is still used (as found in #237), it is not possible to run _install.sh_ script without creating _/home/pi/SUSI.AI_ folder.

A bit history:

- At first, it was assumed that _susi_linux_ stays in _/home/pi/Desktop_. I warned that _Desktop_ is not a normal place to install applications. Other than that, _Desktop_ folder only exists if the distro has Desktop Environment, while our SUSI should be run in headless devices (no DE) as well. Because of this, the location was changed to _/home/pi/SUSI.AI_.
- Now, a new need raises. We need to support factory reset. To make this possible, we will need to change the project structure and installation location. Part of the project (after deployment) must stay in some read-only folders (like _/opt/_, _/usr/local/_). The new location is not decided yet, because I need time to run susi_linux successfully and understand it, and the deployment method needs to be decided as the same time (_apt_ or _snap_). None of these has been finished. But we at least need to make our script neutral to location as much as possible. This is short-term target.

**Pull request merged**
