### PR TITLE
Update media_daemon svg file

### PR DESCRIPTION
**Pull request by prateekiiest**
Update to #286 

screenshot 167

### CODE REVIEW

**Comment by prateekiiest** [comment]
I guess only a portion of the svg got selected on inkscape

**Comment by stealthanthrax** [comment]
@prateekiiest , what is the vertical rectangle in the screenshot??

**Comment by prateekiiest** [comment]
Its actually the page size, how much portion of the svg to be selected. See the svg in the docs folder now of this branch.

**Comment by prateekiiest** [comment]
Let me know if the svg looks ok, I will update the Smart Speaker svg accordingly

**Comment by prateekiiest** [comment]
@stealthanthrax please add a review

**Pull request merged**
