### PR TITLE
Added a 10 second timeout in the recognizing state

### LINKED ISSUE #513: Susi does not leave recognizing state
Susi remains indefinitely in recognizing state, even if nothing is said. We should add a timeout of say 10sec after which it transitions back to idle state.

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #513 
This should work in principle, but since I haven't tested it on my speaker hence still WIP.

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the upstream master branch.
- [x] The unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [x] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
This adds a 10-second timeout in the recognizing state.

#### Changes proposed in this pull request:
Used the threading class to add a timeout

### CODE REVIEW

**Comment by norbusan** [comment]
Looks fine to me. How do you want to proceed?

**Comment by stealthanthrax** [comment]
I'll set up my Speaker again by tomorrow evening and then we can merge it.

**Comment by stealthanthrax** [comment]
This seems to work fine on my side.

**Comment by norbusan** [comment]
Thanks, merged.

**Pull request merged**
