### PR TITLE
build plan action support

### LINKED ISSUE #521: Planned Actions
As a user I want to get timed actions: these are actions which are activated by a given time.
Using timed actions it is possible to make not only "a timer" possible, but it is also possible to activate any kind of actions for a given time.

A broad range of use cases are possible:
- a simple timer which activates a voice message and a sound (two actions, both timed)
- a count-down (many actions, all messages with time-replated text like "20 seconds left")
- a frequent/regular reminder (at 12:00 SUSI says: "it's time to take your pills")
- an alarm clock to wake you up (one music play action at a specific time)
- project planning (family to leave the house at 11:00 - a set of message from "brush your teeth" to "put on your shoes" etc.)

#### Describe the solution you'd like
We need a scheduler which hosts SUSI actions which have time attributes attached. Such an action is not performed at the time when it arrives from the susi_server, instead it is performed if it is due in the scheduler. The due-date is arrived if the local date is greater than the date as given in the "plan" object.

To align the time of the server and the time of the client, the `query_date` as given in the susi response is used. This time is represented in the ISO8601 format and is time-zone independent. 

The "plan" attributes are:
```
        "plan_delay": 60000,
        "plan_date": "2019-07-19T10:52:26.757Z"
```
Here the `delay` value is only used for debugging purpose, it is useful if the timed action was used for a timer; then the delay should represent the timer value in milliseconds.

A full susi response with timed actions would look like:

```

  "query": "set alarm in one minute",
  "query_date": "2019-06-24T13:36:25.490Z",
  "answer_date": "2019-06-24T13:36:25.752Z",
  "answers": [
    {
      "actions": [
      {
        "type": "answer",
        "expression": "Playing Metallica - Nothing Else Matters [Official Music Video]",
        "plan_delay": 60000,
        "plan_date": "2019-07-19T10:52:26.757Z"
      },
      {
        "type": "video_play",
        "identifier_type": "youtube",
        "identifier": "tAGnKpE4NCI",
        "plan_delay": 60000,
        "plan_date": "2019-07-19T10:52:26.757Z"
      },
      {
        "language": "en",
        "type": "answer",
        "expression": "alarm set in one minute to play music"
      }
    ]
  }
 ]
}
```

Here we have 3 Actions!
- one action has no "timed" object and is performed directly
- two actions have (different!) "timed" objects and must be performed later, as given

#### Important
It is NOT sufficient to use the local time of the client and just add up the delay time in milliseconds to compute a local due-time. We want that client can activate actions based on exact times as defined by the skill. This should be as exact as possible to make it feasible that this can be used for machine-to-machine interaction once several machines are using SUSI and communicate using timed events.
Therefore 
- the given due-time must be used as activation moment for the action
- the client must perform a validation check of the local clock with the given `answer_date`: if the local date derives too much from the given `answer_date` the local clock must be corrected to make timed actions possible and exact. Think of this like lives depend on it!!

#### testing
Please use the following link: https://api.susi.ai/susi/chat.json?timezoneOffset=-120&q=set+alarm+in+one+minute

### PR DESCRIPTION
**Pull request by alok760**
Fixes #521

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [ ] The SUSI Server must be building on the pi on bootup
- [ ] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
Implement an action scheduler which schedules planned actions [wip]

### CODE REVIEW

**Comment by alok760** [comment]
Still working on this 
The plan is as follow - 
* if the reply in busy state contains "plan_delay"
* Add the action in that reply to the scheduler. 
* the scheduler then forwards the action to the busy state after the delay.

**Comment by alok760** [comment]
@norbusan please review

**Comment by norbusan** [comment]
What happens if a planned action is triggered right when the speaker is in the busy state, or recognizing state?

**Comment by alok760** [comment]
@norbusan The planned action interrupts the current action and gets executed. So if some other action is being executed in the busy state, it'll stop executing and the planned action will execute.
This is not the ideal way for its working. but is ok for now, maybe in future, we can implement a priority queue for the busy state? what do you suggest?

**Comment by norbusan** [comment]
Merged, thanks

**Pull request merged**
