### PR TITLE
Ported the code according to the library change

### LINKED ISSUE #518: Changing SUSI Python Code
#### Is your feature request related to a problem? Please describe.
Since we are proceeding with SUSI Python, re-structure, we must change the import methods here as well.

#### Describe the solution you'd like
Change the methods according to the new format

#### Additional context
I'll be working on this issue

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #518 

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [x] The unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [x] The hotword detection should have a decent accuracy
- [x] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [x] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
Ports code based on the changes in SUSI Python library

### CODE REVIEW

**Comment by stealthanthrax** [comment]
Dependant PR : https://github.com/fossasia/susi_python/pull/5

**Comment by norbusan** [comment]
Hi @stealthanthrax 
thanks, but I have a few questions and remarks:

- the susi_python PR is outdated wrt to development branch, please fix
- did you test this changes on desktop, or raspi, or both?

Thanks

Norbert

**Comment by stealthanthrax** [comment]
@norbusan , sorry, I did not update the python branch I'll do that asap.

**Comment by stealthanthrax** [comment]
@norbusan , updated

**Pull request merged**
