### PR TITLE
Configured SUSI to run on startup with sound animations

### LINKED ISSUE #310: SUSI not automatically starting after Configuration
**Describe the bug**
SUSI is expected to run automatically after mobile configuration is complete

**To Reproduce**
Complete the configuration and wait for a restart

**Expected behavior**
To make it run automatically

**Additional context**
I would like to work on it

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #310 

This now enables SUSI on startup mode along with voice animations and starts factory reset daemon along with it

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@prateekiiest , have a look too

**Comment by stealthanthrax** [comment]
@hongquan , I did that but `python3 -m main` command doesn't work. So, I had to wrap it another bash script

**Comment by hongquan** [comment]
> I did that but python3 -m main command doesn't work in systemd rules

Again? You always say "doesn't work" without any attempt to debug and always choose to do workaround, avoid finding the root cause!

**Comment by stealthanthrax** [comment]
@hongquan , I tried debugging a lot. But I could find no way of running a python module directly from a Systemd file without wrapping it in a bash script.

**Comment by hongquan** [comment]
> I could find no way of running a python module directly from a Systemd file 

@stealthanthrax How did you write your systemd service file?

**Comment by stealthanthrax** [comment]
@hongquan , I used this command `ExecStart=/usr/bin/python3 -m  /home/pi/SUSI.AI/susi_linux/main`

**Comment by hongquan** [comment]
@stealthanthrax I want the WHOLE file!

**Comment by stealthanthrax** [comment]
@hongquan , it's in the Systemd folder in the current repo this [file](https://github.com/fossasia/susi_linux/blob/master/Deploy/Systemd/ss-python-flask.service)

**Comment by hongquan** [comment]
https://github.com/fossasia/susi_linux/blob/1966caa07b0bd59c90a13b4b324231561daea42b/Deploy/Systemd/ss-python-flask.service#L7

Problem:

- Incorrect syntax to run a python module (and you blamed _systemd_ for your error?)
- Your module is not installed to Python's path. Invoking with plain `-m your_module` will fail because Python can not find where `your_module` is. When you run manually (type the command to terminal), it runs because you start from _susi\_linux_, where Python can find the module. "Current directory" is the first location that Python will look for modules. If the command is run by _systemd_, it starts from "/", so Python cannot find the module. Read systemd doc to know how to change working directory.

**Comment by Orbiter** [comment]
Please @/all review ASAP I would consider to merge this tomorrow otherwise to move on.

**Comment by hongquan** [comment]
@stealthanthrax Please fix the command line:

```ini
ExecStart=/usr/bin/python3 -m  /home/pi/SUSI.AI/susi_linux/main 
```

This is not correct command to run Python script or module.

**Comment by stealthanthrax** [comment]
@hongquan , I couldn't figure out a way to run python modules from systemd files. I tried changing the directory but still couldn't run it. Also, it not very well documented. Hence am using a bash script to play SUSI. Please if you could suggest the correct syntax

**Comment by hongquan** [comment]
@stealthanthrax The correct syntax is in the bash script.

image


If you know that the bash script works, and you are writing wrong syntax in systemd, why don't you just look into the bash script to see the correct syntax?

**Comment by hongquan** [comment]
> I couldn't figure out a way to run python modules from systemd files. I tried changing the directory but still couldn't run it. Also, it not very well documented

systemd is well documented enough. What you did wrong is your wrong Python command line. How to using Python correctly is Python user's business, not systemd business. Systemd doesn't have responsibility to tell you how to use Python correctly!

**Comment by hongquan** [comment]
Doc: https://docs.python.org/3.6/using/cmdline.html#cmdoption-m

**Comment by Orbiter** [comment]
So what is the status now, should we merge this? If this is not working right now, please fix it. If it IS working and those python issues are just cosmetic, we should merge this and I would like ask @hongquan to make required changes afterwards.

**Comment by stealthanthrax** [comment]
@hongquan , I don´t understand . Can you please rephrase ??
> If you know that the bash script works, and you are writing wrong syntax in systemd, why don't you just look into the bash script to see the correct syntax?

**Comment by hongquan** [comment]
@stealthanthrax This is your **wrong** syntax:

```
python3 -m  /home/pi/SUSI.AI/susi_linux/main
```

and this is the **correct** syntax, which appears in https://github.com/fossasia/susi_linux/blob/38fe9b4a89c6f99209c7cfb99cabeeb7d6000ac5/run.sh#L8

You still cannot see the difference between

```
-m  /home/pi/SUSI.AI/susi_linux/main
```
and

```
-m  main
```

???

**Comment by stealthanthrax** [comment]
@hongquan , updated

**Pull request merged**
