### PR TITLE
Update the media_daemon workflow svg

### PR DESCRIPTION
**Pull request by prateekiiest**
Looks like this

screenshot 159

### CODE REVIEW

**Comment by prateekiiest** [comment]
@hongquan @Orbiter @mariobehling @stealthanthrax @cweitat @woshikie reviews please

**Comment by prateekiiest** [comment]
the aspect ratio of the image?

**Comment by stealthanthrax** [comment]
No  @prateekiiest . I am referring to the lines of code that are being rendered in the image. You can see that all the prvious svg related code was shrunk to one line . This will maintain the efficiency of the rendering code

**Comment by hongquan** [comment]
Need to rework, like https://github.com/fossasia/susi_linux/pull/290.

**Pull request merged**
