### PR TITLE
Added white light control for RaspberryPi

### LINKED ISSUE #395: Random White Lights are turned ON on the piHat on boot
**Describe the bug**
Sometimes, when the Raspberry Pi is started there is a white light indication on the ReSpeaker

**To Reproduce**
Steps to reproduce the behaviour:
1. Attach the ReSpeaker
2. Boot your RPi
3. Keep rebooting until you see the white light

**Expected behaviour**
No "random" light should  be there. A decided animation can be added.

**Additional context**
I'd like to work on this

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #395

No random white light is generated anymore

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@hongquan , it's the default behaviour of the piHat. Not of anything installed via SUSI Linux

**Comment by hongquan** [comment]
Reflash your RPi with original Raspbian Lite and check how is the LED.

**Comment by hongquan** [comment]
Ok. The ReSpeaker author [confirms](https://github.com/respeaker/seeed-voicecard/issues/37#issuecomment-368762762) that the VoiceCard's LED is ON by default and has to be turned off by additional script.

**Comment by cweitat** [comment]
@stealthanthrax travis failed

**Comment by stealthanthrax** [comment]
@cweitat , updated

**Pull request merged**
