### PR TITLE
Update the SUSI Smart Speaker Workflow

### LINKED ISSUE #229: Create proper vector SVG image
**Describe the bug**
@prateekiiest , when @mariobehling tell you to make diagram document in SVG, he wants a vector image, so that it comes as "source", can be edited, and can be scale. But why you make it in bitmap and just embed to SVG file? This is not honest.

**Expected behavior**
The file is a true SVG image, with lines and shapes being made by SVG code.

**Screenshots**
Current SVG source:

image

image

### PR DESCRIPTION
**Pull request by prateekiiest**
Fixes #229
The workflow svg

### CODE REVIEW

**Comment by woshikie** [comment]
is this for #229?

**Comment by prateekiiest** [comment]
yup

**Comment by prateekiiest** [comment]
I could have also updated the svg for gemnasium dependancy status.
But it seems gemnasium has closed. Any other alternative?

**Comment by hongquan** [comment]
This is text object

image

**Comment by prateekiiest** [comment]
@hongquan I had the png image of the workflow. Hence I used it to convert into svg format and use it. If we need to change it we can modify the png image (the png image can be edited in an editor and downloaded as png) and then we can use it as suitable svg.

Since we already had the previous workflow in png format, I just used it to convert into corresponding svg format. But if you wish I can work on creating direct svg from Inkscape , so that its editable without having to be converted from png to svg.

**Comment by hongquan** [comment]
Yes, the point of creating doc in SVG because:

- It is vector graphic, can scale.
- It is open format, anyone can edit, without buying commercial software (like Corel Draw, AI).
- It is text based, so it can stored text efficiently (aren't we are making "doc"?).
- It is text based, so its version can be managed by Git.

**Comment by prateekiiest** [comment]
Ok @hongquan , I am working on it.
It may take time, since I have to make the design in svg from scratch on Inkscape.
I will try my best to finish quickly

**Comment by hongquan** [comment]
No need to make it fancy. Text with lines and retangulars are enough.

Also not hurry.

**Comment by prateekiiest** [comment]
I was having some problems regarding creating the arrows on inkscape. Maybe some help will be good

**Comment by hongquan** [comment]
I don't understand what you mean by "creating arrow" that make you feel difficult.

Isn't this tool is not what you want?

image

**Comment by prateekiiest** [comment]
Inkscape does not support a convenient support for stretching arrows and hence a lot of times, when I try to increase the font of the array through stretching, its getting bended .

Also, the end point for the arrow (the tail) only gets connected to the corners of the boxes containing information and not on the middle of the edges of the boxes as in the png image.

**Comment by hongquan** [comment]
I don't see what you are trying to do, so not very understand your use case.

> Inkscape does not support a convenient support for stretching arrows and hence a lot of times, when I try to increase the font of the array through stretching, its getting bended 

Why do you have to stretch? Why not use the proper methods: make wrap box bigger, set line thickness bigger, increase font size?

> Also, the end point for the arrow (the tail) only gets connected to the corners of the boxes containing information and not on the middle of the edges of the boxes as in the png image.

The arrow has its own box. If you want to point the arrow to somewhere (middle of png), why not just adjusting the size of arrow box?

**Pull request merged**
