### PR TITLE
Bug Fix with music Server

### LINKED ISSUE #413: Song not played due to wrong communication
**Describe the bug**

This bug is introduced by #391.
When speaking to susi_linux: "play cheerleader", the main module calls music_server API with "/song/ytd-jGflUbPQfW8" URL. But this URL is not recognized by music_server.

The code
https://github.com/fossasia/susi_linux/blob/06fd30002091e3422252040d526180643abc066c/youtube_player/music_server.py#L15-L17

clearly shows that, this module expects URL as `/song?vid=jGflUbPQfW8`, not `/song/ytd-jGflUbPQfW8`.

I doubt @stealthanthrax carefully tested his code before making PR.

**To Reproduce**
1. Stop susi_linux systemd service
2. Run susi_linux manually (with command `python3 -m main`)
3. Run `journalctl -fu ss-susi-youtube.service` to see this service's log.
4. Speak "susi play cheerleader" to SUSI (actually, I spoke "susi play soledad", but Google STT somehow misunderstood me).
5. Look into _ss-susi-youtube.service_ log, I saw this log:

```
Nov 12 18:38:31 quan-pi-two python3[5814]: 127.0.0.1 - - [12/Nov/2018 18:38:31] "GET /song/ytd-jGflUbPQfW8 HTTP/1.1" 404 -
```

**Expected behavior**
susi_linux main module should call correct URL and the song is played.

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #413 

Minor Bug fix in vlc music server.

### CODE REVIEW

**Comment by hongquan** [comment]
Please provide a evidence that you tested your fixed code.

**Comment by stealthanthrax** [comment]
I am at my Uni Hostel RN, will provide the working video till weekend
> Please provide a evidence that you tested your fixed code.

**Comment by hongquan** [comment]
@stealthanthrax Provide the log first, log of `python -m main` and log of music server.

**Comment by stealthanthrax** [comment]
Here is the log
screenshot 2018-11-17 at 2 40 06 am

**Comment by hongquan** [comment]
@stealthanthrax  You lack the log of music server

**Comment by stealthanthrax** [comment]
screenshot 2018-11-17 at 5 17 31 pm

**Comment by hongquan** [comment]
Good.

**Pull request merged**
