### PR TITLE
very very minor change

### PR DESCRIPTION
**Pull request by xeon-zolt**
changed an if else condition to a one-liner

Fixes #

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [x] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [ ] The SUSI Server must be building on the pi on bootup
- [ ] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
just converted if else to a oneliner
#### Changes proposed in this pull request:
reduced no of lines in the code

### CODE REVIEW

**Comment by hongquan** [comment]
I don't understand why you have to write:

```py
return [False, True][api_response.status_code == 200]
```

Isn't this better:

```py
return (api_response.status_code == 200)
```

**Comment by xeon-zolt** [comment]
I was reading the code and just thought why not

**Comment by stealthanthrax** [comment]
Didn't read @hongquan 's suggestion before approval. Either one looks good to me.

**Comment by norbusan** [comment]
Please use 
```
return (api_response.status_code == 200)
```
the index arraying approach is unreadable!

**Comment by norbusan** [comment]
Thanks, merged.

**Pull request merged**
